# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # Les options valides de drivers incluent "gd" ou "gmagick" ou "imagick"
    driver: "gd"

    #jeux de filtres
    filter_sets:
        # chaque filtre reçoit un nom
        
        # filtre pour incruster une photo miniature 
        miniature:
            quality: 75  		        #qualité de l'image (taux de compression)
            filters: 		            # filtres à utiliser
                thumbnail :             # faire une vignette
                    size: [100, 100]    # retailler en hauteur et largeur
                    mode: outbound
        
        # filtre pour incruster une photo dans le format souhaité
        vignette:
            quality: 85
            filters:
                scale:
                    dim: [250, 250]   #gère automatiquement soit la hauteur soit la largeur

        # filtre pour une photo grand format en tête de page
        photo_page:
            quality: 85
            filters:
                scale:                  # agrandit si image trop petite
                    min: [800, 300]     #taille minimum 
                thumbnail:
                    size: [800, 300]
                    mode: outbound
                    # bordure de 2px noir: centre le thumbnail dans un fond
                    # 4px plus large fait une bordure de 2px autour de l' image
                background :
                    size : [804, 304]
                    position : center
                    color : '#000000'

        # filtre pour une illustration d'article
        photo_article:
            quality: 85
            filters:
                scale:                  # agrandit si image trop petite
                    min: [300, 100]     #taille minimum 
                thumbnail:
                    size: [300, 100]
                    mode: outbound